2018-04-15 11:11:50,328 [Thread-8:2104] [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-04-15 11:12:26,696 [Thread-14:8548] [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-04-15 17:26:59,126 [Thread-13:16504] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonworkspace\blog_project\blog\views.py", line 9, in index
    return render(request, 'index.html', locals())
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 182, in render
    template = context.template.engine.get_template(template_name)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 539, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 5: 'static'. Did you forget to register or load this tag?
2018-04-15 17:33:17,139 [Thread-96:18436] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/category/1/delete/
Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`blogdb`.`blog_article`, CONSTRAINT `blog_article_category_id_7e38f15e_fk_blog_category_id` FOREIGN KEY (`category_id`) REFERENCES `blog_category` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\contrib\admin\options.py", line 574, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\utils\decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\utils\decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\contrib\admin\options.py", line 1713, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\contrib\admin\options.py", line 1746, in _delete_view
    self.delete_model(request, obj)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\contrib\admin\options.py", line 1032, in delete_model
    obj.delete()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\models\base.py", line 891, in delete
    return collector.delete()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\models\deletion.py", line 301, in delete
    count = query.delete_batch(pk_list, self.using)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\models\sql\subqueries.py", line 41, in delete_batch
    num_deleted += self.do_query(self.get_meta().db_table, self.where, using=using)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\models\sql\subqueries.py", line 24, in do_query
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1064, in execute_sql
    cursor.execute(sql, params)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`blogdb`.`blog_article`, CONSTRAINT `blog_article_category_id_7e38f15e_fk_blog_category_id` FOREIGN KEY (`category_id`) REFERENCES `blog_category` (`id`))')
2018-04-15 17:33:50,698 [Thread-97:16288] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/category/1/delete/
Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`blogdb`.`blog_article`, CONSTRAINT `blog_article_category_id_7e38f15e_fk_blog_category_id` FOREIGN KEY (`category_id`) REFERENCES `blog_category` (`id`))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\contrib\admin\options.py", line 574, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\contrib\admin\sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\utils\decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\utils\decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\contrib\admin\options.py", line 1713, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\contrib\admin\options.py", line 1746, in _delete_view
    self.delete_model(request, obj)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\contrib\admin\options.py", line 1032, in delete_model
    obj.delete()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\models\base.py", line 891, in delete
    return collector.delete()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\models\deletion.py", line 301, in delete
    count = query.delete_batch(pk_list, self.using)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\models\sql\subqueries.py", line 41, in delete_batch
    num_deleted += self.do_query(self.get_meta().db_table, self.where, using=using)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\models\sql\subqueries.py", line 24, in do_query
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1064, in execute_sql
    cursor.execute(sql, params)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\cursors.py", line 165, in execute
    result = self._query(query)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1061, in _read_query_result
    result.read()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 1018, in _read_packet
    packet.check_error()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`blogdb`.`blog_article`, CONSTRAINT `blog_article_category_id_7e38f15e_fk_blog_category_id` FOREIGN KEY (`category_id`) REFERENCES `blog_category` (`id`))')
2018-04-15 19:24:09,066 [Thread-9:16396] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:/pythonworkspace/blog_project\blog\views.py", line 30, in index
    return render(request, 'index.html', locals())
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 194, in render
    return template.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\templatetags\static.py", line 106, in render
    url = self.url(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\templatetags\static.py", line 103, in url
    return self.handle_simple(path)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\templatetags\static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\files\storage.py", line 329, in url
    url = filepath_to_uri(name)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\utils\encoding.py", line 252, in filepath_to_uri
    return quote(path.replace("\\", "/"), safe="/~!*()'")
AttributeError: 'ImageFieldFile' object has no attribute 'replace'
2018-04-15 19:31:22,521 [Thread-38:2124] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:/pythonworkspace/blog_project\blog\views.py", line 30, in index
    return render(request, 'index.html', locals())
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 182, in render
    template = context.template.engine.get_template(template_name)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
2018-04-15 19:38:34,523 [Thread-58:18120] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:/pythonworkspace/blog_project\blog\views.py", line 30, in index
    return render(request, 'index.html', locals())
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 194, in render
    return template.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\urls\resolvers.py", line 632, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '/uploads/ad/2018/04/a1.jpg' not found. '/uploads/ad/2018/04/a1.jpg' is not a valid view function or pattern name.
2018-04-15 19:39:00,651 [Thread-59:10392] [django.request:93] [base:get_response] [WARNING]- Not Found: //uploads/ad/2018/04/a1.jpg
2018-04-15 19:39:39,747 [Thread-63:13872] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\defaulttags.py", line 1025, in find_library
    return parser.libraries[name]
KeyError: 'ad.image_url.url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:/pythonworkspace/blog_project\blog\views.py", line 30, in index
    return render(request, 'index.html', locals())
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 182, in render
    template = context.template.engine.get_template(template_name)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\defaulttags.py", line 1082, in load
    lib = find_library(parser, name)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\defaulttags.py", line 1029, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'ad.image_url.url' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
static
staticfiles
tz
2018-04-15 19:40:11,241 [Thread-64:10076] [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'src'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:/pythonworkspace/blog_project\blog\views.py", line 30, in index
    return render(request, 'index.html', locals())
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loader_tags.py", line 182, in render
    template = context.template.engine.get_template(template_name)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "F:\pythonworkspace\djangodemo\venv\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'src', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
